name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./StackOverflowTag
    
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./StackOverflowTag
    
    - name: Unit Tests
      run: dotnet test --no-restore --verbosity normal --filter Category=UnitTest
      working-directory: ./StackOverflowTagsTest
    
    - name: Integration Tests
      run: dotnet test --no-restore --verbosity normal --filter Category=IntegrationTest
      working-directory: ./StackOverflowTagsTest

    - name: Lint
      run: dotnet format --verify-no-changes --verbosity diagnostic

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./StackOverflowTag
